"""Script generation for the meme channel's gameplay-backdrop format: an
LLM-written joke/observation narration with a continuous, unrelated
hyperstimulating gameplay clip (Subway Surfers, Minecraft parkour, ...)
running underneath, via src/pipeline/brainrot.py. The visual is decorative
background, not tied to the script's content, so unlike every other channel
there's no keyword search or grounding step -- this is pure comedy writing.
"""

from src.pipeline.brainrot import random_background_marker
from src.pipeline.llm import chat_json

SYSTEM = """You write short, funny narrated scripts for faceless short-form video \
(YouTube Shorts / Instagram Reels), meant to be genuinely funny to a real \
audience -- not awkward, not cringe, not "AI slop" that gets people annoyed \
it's obviously AI-written. Output strict JSON with one key:
- "script": narration text only, spoken conversationally, 70-110 words (about \
30-45 seconds).
  - Open with the funniest or most relatable line as the first sentence -- no \
windup, no "so today we're talking about," no throat-clearing.
  - Write like a genuinely funny friend telling a story or making an \
observation, not a comedian reading jokes off a card. Real rhythm and timing, \
contractions, short punchy lines. Vary sentence length; a one-word sentence \
after a long one lands harder than two medium ones in a row.
  - Formats that work well: a relatable "type of person who..." observation, a \
short absurd story with a punchline, a rapid-fire list of oddly specific \
relatable moments, a deadpan take on something everyone secretly agrees with.
  - End on the punchline or the funniest line, not a trailing-off summary.
  - No stage directions, no headings, no emojis, no hashtags, and nothing that \
reads as generated by AI -- no "in today's fast-paced world," no forced puns, \
no over-explaining the joke afterward."""


def generate_meme_content(topic: str, config: dict, state: dict) -> dict:
    result = chat_json(SYSTEM, f"Topic: {topic}\n\nWrite the script now.", model=config["llm"]["model"])
    if "script" not in result:
        raise ValueError(f"Unexpected LLM response shape: {result}")
    # The prompt asks for 70-110 words; an occasional runaway generation can
    # come back far longer, which silently turns into a multi-minute video
    # and a very slow ffmpeg encode downstream. Fail fast here instead.
    word_count = len(result["script"].split())
    if word_count > 250:
        raise ValueError(f"LLM script way over length ({word_count} words) — likely a runaway generation")

    return {
        "script": result["script"],
        "media_urls": [random_background_marker(duration=60)],
        "visual_mode": "media",
        "hook_id": None,
        "attribution": "Background gameplay via public compilation footage",
    }
