"""Script generation for the meme channel, which rotates two formats:

- Plain topics (from topics.txt): gameplay-backdrop "brainrot" -- an LLM-
  written joke/observation narration with a continuous, unrelated
  hyperstimulating gameplay clip (Subway Surfers, Minecraft parkour, ...)
  running underneath, via src/pipeline/brainrot.py. The visual is decorative
  background, never tied to the script's content, so there's no keyword
  search or grounding step here -- just comedy writing.
- The literal topic "AI_CHARACTER": Italian-Brainrot-style surreal-creature
  content, where the LLM writes both the narration and a matching image
  prompt, rendered by src/pipeline/image_gen.py (Cloudflare Workers AI).
  This is the one deliberately-AI-generated visual in this whole project --
  every other channel sources real images/footage on purpose (see
  feedback_sourced_not_generated_images) -- because this specific genre's
  entire appeal is being openly, unmistakably AI-generated, so it doesn't
  read as the "AI slop" the rest of this project is built to avoid.
"""

from urllib.parse import quote

from src.pipeline.brainrot import random_background_marker
from src.pipeline.llm import chat_json

SYSTEM = """You write short, funny narrated scripts for faceless short-form video \
(YouTube Shorts / Instagram Reels), meant to be genuinely funny to a real \
audience -- not awkward, not cringe, not "AI slop" that gets people annoyed \
it's obviously AI-written. Output strict JSON with one key:
- "script": narration text only, spoken conversationally, 70-110 words (about \
30-45 seconds).
  - Open with the funniest or most relatable line as the first sentence -- no \
windup, no "so today we're talking about," no throat-clearing.
  - Write like a genuinely funny friend telling a story or making an \
observation, not a comedian reading jokes off a card. Real rhythm and timing, \
contractions, short punchy lines. Vary sentence length; a one-word sentence \
after a long one lands harder than two medium ones in a row.
  - Formats that work well: a relatable "type of person who..." observation, a \
short absurd story with a punchline, a rapid-fire list of oddly specific \
relatable moments, a deadpan take on something everyone secretly agrees with.
  - End on the punchline or the funniest line, not a trailing-off summary.
  - No stage directions, no headings, no emojis, no hashtags, and nothing that \
reads as generated by AI -- no "in today's fast-paced world," no forced puns, \
no over-explaining the joke afterward."""

SYSTEM_AI_CHARACTER = """You write short "character introduction" scripts in the \
"Italian Brainrot" internet meme style -- absurd creature/object mashups with \
nonsense Italian-sounding names, narrated completely deadpan like a nature \
documentary about something ridiculous. Output strict JSON with two keys:
- "script": narration text only, spoken conversationally, 60-90 words (about \
25-35 seconds). Introduce the creature by its nonsense name, describe its absurd \
hybrid appearance and one ridiculous "fact" or "power" about it, matter-of-fact \
as if this is completely normal. No stage directions, no headings, no emojis, no \
hashtags.
- "image_prompt": a vivid 2-3 sentence visual description for an AI image \
generator to render this exact creature -- specific about which real objects/ \
animals are mashed together, the setting, and the style (photorealistic 3D \
render, dramatic lighting, plain background, subject centered and filling the \
frame since the output gets cropped to a tall portrait)."""


def _generate_ai_character(config: dict) -> dict:
    result = chat_json(SYSTEM_AI_CHARACTER, "Invent one now and write it.", model=config["llm"]["model"])
    if "script" not in result or "image_prompt" not in result:
        raise ValueError(f"Unexpected LLM response shape: {result}")
    word_count = len(result["script"].split())
    if word_count > 200:
        raise ValueError(f"LLM script way over length ({word_count} words) — likely a runaway generation")
    return result


def generate_meme_content(topic: str, config: dict, state: dict) -> dict:
    if topic.strip().upper() == "AI_CHARACTER":
        result = _generate_ai_character(config)
        marker = f"ai-image://{quote(result['image_prompt'])}"
        return {
            "script": result["script"],
            "media_urls": [marker],
            "visual_mode": "media",
            "hook_id": None,
            "attribution": "Character art generated with Cloudflare Workers AI (Flux)",
        }

    result = chat_json(SYSTEM, f"Topic: {topic}\n\nWrite the script now.", model=config["llm"]["model"])
    if "script" not in result:
        raise ValueError(f"Unexpected LLM response shape: {result}")
    # The prompt asks for 70-110 words; an occasional runaway generation can
    # come back far longer, which silently turns into a multi-minute video
    # and a very slow ffmpeg encode downstream. Fail fast here instead.
    word_count = len(result["script"].split())
    if word_count > 250:
        raise ValueError(f"LLM script way over length ({word_count} words) — likely a runaway generation")

    return {
        "script": result["script"],
        "media_urls": [random_background_marker(duration=60)],
        "visual_mode": "media",
        "hook_id": None,
        "attribution": "Background gameplay via public compilation footage",
    }
